// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNeu2W7dFOE6kZmP-NqNqYVBNDBbsnAiA',
    appId: '1:849572262038:web:dae0be5f196b7a66b792b7',
    messagingSenderId: '849572262038',
    projectId: 'vsquareclasses-e8e78',
    authDomain: 'vsquareclasses-e8e78.firebaseapp.com',
    storageBucket: 'vsquareclasses-e8e78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEgIGDS1rZgJr3pfSvOg3AV1nZ2LZ5YhM',
    appId: '1:849572262038:android:f3b89f1984f8712eb792b7',
    messagingSenderId: '849572262038',
    projectId: 'vsquareclasses-e8e78',
    storageBucket: 'vsquareclasses-e8e78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDojps6BWc-9oyXaYW84VDSp-AOmY2sP3A',
    appId: '1:849572262038:ios:fe9c2137d0a58e97b792b7',
    messagingSenderId: '849572262038',
    projectId: 'vsquareclasses-e8e78',
    storageBucket: 'vsquareclasses-e8e78.appspot.com',
    iosBundleId: 'com.ygsd.vsquareclasses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDojps6BWc-9oyXaYW84VDSp-AOmY2sP3A',
    appId: '1:849572262038:ios:697112172385cc8cb792b7',
    messagingSenderId: '849572262038',
    projectId: 'vsquareclasses-e8e78',
    storageBucket: 'vsquareclasses-e8e78.appspot.com',
    iosBundleId: 'com.ygsd.vsquareclasses.RunnerTests',
  );
}
